// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GENOME_EVOLUTION_GENOME_H_
#define FLATBUFFERS_GENERATED_GENOME_EVOLUTION_GENOME_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace evolution {
namespace genome {

struct Vec3F;
struct Vec3FBuilder;

struct Joint;
struct JointBuilder;

struct BodyNode;
struct BodyNodeBuilder;

struct MLP;
struct MLPBuilder;

struct NeatNode;
struct NeatNodeBuilder;

struct NeatConn;
struct NeatConnBuilder;

struct NEAT;
struct NEATBuilder;

struct ModulePlasticity;
struct ModulePlasticityBuilder;

struct BrainModule;
struct BrainModuleBuilder;

struct BrainGating;
struct BrainGatingBuilder;

struct PreferenceNet;
struct PreferenceNetBuilder;

struct Mutator;
struct MutatorBuilder;

struct LifeStage;
struct LifeStageBuilder;

struct TraitsCache;
struct TraitsCacheBuilder;

struct Genome;
struct GenomeBuilder;

enum ShapeType : uint8_t {
  ShapeType_Sphere = 0,
  ShapeType_CapsuleY = 1,
  ShapeType_Box = 2,
  ShapeType_MIN = ShapeType_Sphere,
  ShapeType_MAX = ShapeType_Box
};

inline const ShapeType (&EnumValuesShapeType())[3] {
  static const ShapeType values[] = {
    ShapeType_Sphere,
    ShapeType_CapsuleY,
    ShapeType_Box
  };
  return values;
}

inline const char * const *EnumNamesShapeType() {
  static const char * const names[4] = {
    "Sphere",
    "CapsuleY",
    "Box",
    nullptr
  };
  return names;
}

inline const char *EnumNameShapeType(ShapeType e) {
  if (::flatbuffers::IsOutRange(e, ShapeType_Sphere, ShapeType_Box)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesShapeType()[index];
}

enum BrainKind : uint8_t {
  BrainKind_MLP = 0,
  BrainKind_NEAT = 1,
  BrainKind_MIN = BrainKind_MLP,
  BrainKind_MAX = BrainKind_NEAT
};

inline const BrainKind (&EnumValuesBrainKind())[2] {
  static const BrainKind values[] = {
    BrainKind_MLP,
    BrainKind_NEAT
  };
  return values;
}

inline const char * const *EnumNamesBrainKind() {
  static const char * const names[3] = {
    "MLP",
    "NEAT",
    nullptr
  };
  return names;
}

inline const char *EnumNameBrainKind(BrainKind e) {
  if (::flatbuffers::IsOutRange(e, BrainKind_MLP, BrainKind_NEAT)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesBrainKind()[index];
}

enum NodeType : uint8_t {
  NodeType_Input = 0,
  NodeType_Hidden = 1,
  NodeType_Output = 2,
  NodeType_MIN = NodeType_Input,
  NodeType_MAX = NodeType_Output
};

inline const NodeType (&EnumValuesNodeType())[3] {
  static const NodeType values[] = {
    NodeType_Input,
    NodeType_Hidden,
    NodeType_Output
  };
  return values;
}

inline const char * const *EnumNamesNodeType() {
  static const char * const names[4] = {
    "Input",
    "Hidden",
    "Output",
    nullptr
  };
  return names;
}

inline const char *EnumNameNodeType(NodeType e) {
  if (::flatbuffers::IsOutRange(e, NodeType_Input, NodeType_Output)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNodeType()[index];
}

enum Activation : uint8_t {
  Activation_Linear = 0,
  Activation_Tanh = 1,
  Activation_Relu = 2,
  Activation_Sigmoid = 3,
  Activation_MIN = Activation_Linear,
  Activation_MAX = Activation_Sigmoid
};

inline const Activation (&EnumValuesActivation())[4] {
  static const Activation values[] = {
    Activation_Linear,
    Activation_Tanh,
    Activation_Relu,
    Activation_Sigmoid
  };
  return values;
}

inline const char * const *EnumNamesActivation() {
  static const char * const names[5] = {
    "Linear",
    "Tanh",
    "Relu",
    "Sigmoid",
    nullptr
  };
  return names;
}

inline const char *EnumNameActivation(Activation e) {
  if (::flatbuffers::IsOutRange(e, Activation_Linear, Activation_Sigmoid)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesActivation()[index];
}

/// Dietary preference that determines what entities can be consumed for energy.
enum DietPreference : uint8_t {
  /// Consumes plants only.
  DietPreference_Herbivore = 0,
  /// Consumes other creatures only.
  DietPreference_Carnivore = 1,
  /// Can consume both (future: reduced efficiency).
  DietPreference_Omnivore = 2,
  DietPreference_MIN = DietPreference_Herbivore,
  DietPreference_MAX = DietPreference_Omnivore
};

inline const DietPreference (&EnumValuesDietPreference())[3] {
  static const DietPreference values[] = {
    DietPreference_Herbivore,
    DietPreference_Carnivore,
    DietPreference_Omnivore
  };
  return values;
}

inline const char * const *EnumNamesDietPreference() {
  static const char * const names[4] = {
    "Herbivore",
    "Carnivore",
    "Omnivore",
    nullptr
  };
  return names;
}

inline const char *EnumNameDietPreference(DietPreference e) {
  if (::flatbuffers::IsOutRange(e, DietPreference_Herbivore, DietPreference_Omnivore)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDietPreference()[index];
}

enum JointType : uint8_t {
  JointType_Fixed = 0,
  JointType_Hinge = 1,
  JointType_Spherical = 2,
  JointType_MIN = JointType_Fixed,
  JointType_MAX = JointType_Spherical
};

inline const JointType (&EnumValuesJointType())[3] {
  static const JointType values[] = {
    JointType_Fixed,
    JointType_Hinge,
    JointType_Spherical
  };
  return values;
}

inline const char * const *EnumNamesJointType() {
  static const char * const names[4] = {
    "Fixed",
    "Hinge",
    "Spherical",
    nullptr
  };
  return names;
}

inline const char *EnumNameJointType(JointType e) {
  if (::flatbuffers::IsOutRange(e, JointType_Fixed, JointType_Spherical)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesJointType()[index];
}

struct Vec3F FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Vec3FBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6,
    VT_Z = 8
  };
  float x() const {
    return GetField<float>(VT_X, 0.0f);
  }
  float y() const {
    return GetField<float>(VT_Y, 0.0f);
  }
  float z() const {
    return GetField<float>(VT_Z, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_X, 4) &&
           VerifyField<float>(verifier, VT_Y, 4) &&
           VerifyField<float>(verifier, VT_Z, 4) &&
           verifier.EndTable();
  }
};

struct Vec3FBuilder {
  typedef Vec3F Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(float x) {
    fbb_.AddElement<float>(Vec3F::VT_X, x, 0.0f);
  }
  void add_y(float y) {
    fbb_.AddElement<float>(Vec3F::VT_Y, y, 0.0f);
  }
  void add_z(float z) {
    fbb_.AddElement<float>(Vec3F::VT_Z, z, 0.0f);
  }
  explicit Vec3FBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Vec3F> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Vec3F>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Vec3F> CreateVec3F(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float x = 0.0f,
    float y = 0.0f,
    float z = 0.0f) {
  Vec3FBuilder builder_(_fbb);
  builder_.add_z(z);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

struct Joint FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef JointBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_AXIS = 6,
    VT_LIMITS = 8,
    VT_ANCHOR = 10
  };
  evolution::genome::JointType type() const {
    return static_cast<evolution::genome::JointType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  const evolution::genome::Vec3F *axis() const {
    return GetPointer<const evolution::genome::Vec3F *>(VT_AXIS);
  }
  const evolution::genome::Vec3F *limits() const {
    return GetPointer<const evolution::genome::Vec3F *>(VT_LIMITS);
  }
  const evolution::genome::Vec3F *anchor() const {
    return GetPointer<const evolution::genome::Vec3F *>(VT_ANCHOR);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_AXIS) &&
           verifier.VerifyTable(axis()) &&
           VerifyOffset(verifier, VT_LIMITS) &&
           verifier.VerifyTable(limits()) &&
           VerifyOffset(verifier, VT_ANCHOR) &&
           verifier.VerifyTable(anchor()) &&
           verifier.EndTable();
  }
};

struct JointBuilder {
  typedef Joint Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(evolution::genome::JointType type) {
    fbb_.AddElement<uint8_t>(Joint::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_axis(::flatbuffers::Offset<evolution::genome::Vec3F> axis) {
    fbb_.AddOffset(Joint::VT_AXIS, axis);
  }
  void add_limits(::flatbuffers::Offset<evolution::genome::Vec3F> limits) {
    fbb_.AddOffset(Joint::VT_LIMITS, limits);
  }
  void add_anchor(::flatbuffers::Offset<evolution::genome::Vec3F> anchor) {
    fbb_.AddOffset(Joint::VT_ANCHOR, anchor);
  }
  explicit JointBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Joint> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Joint>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Joint> CreateJoint(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    evolution::genome::JointType type = evolution::genome::JointType_Fixed,
    ::flatbuffers::Offset<evolution::genome::Vec3F> axis = 0,
    ::flatbuffers::Offset<evolution::genome::Vec3F> limits = 0,
    ::flatbuffers::Offset<evolution::genome::Vec3F> anchor = 0) {
  JointBuilder builder_(_fbb);
  builder_.add_anchor(anchor);
  builder_.add_limits(limits);
  builder_.add_axis(axis);
  builder_.add_type(type);
  return builder_.Finish();
}

struct BodyNode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BodyNodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SHAPE = 4,
    VT_SIZE = 6,
    VT_MASS_DENSITY = 8,
    VT_COLOR = 10,
    VT_CHILDREN = 12,
    VT_JOINT_TO_PARENT = 14,
    VT_TRANSFORM = 16
  };
  evolution::genome::ShapeType shape() const {
    return static_cast<evolution::genome::ShapeType>(GetField<uint8_t>(VT_SHAPE, 0));
  }
  const evolution::genome::Vec3F *size() const {
    return GetPointer<const evolution::genome::Vec3F *>(VT_SIZE);
  }
  float mass_density() const {
    return GetField<float>(VT_MASS_DENSITY, 0.0f);
  }
  const evolution::genome::Vec3F *color() const {
    return GetPointer<const evolution::genome::Vec3F *>(VT_COLOR);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::BodyNode>> *children() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::BodyNode>> *>(VT_CHILDREN);
  }
  const evolution::genome::Joint *joint_to_parent() const {
    return GetPointer<const evolution::genome::Joint *>(VT_JOINT_TO_PARENT);
  }
  const evolution::genome::Vec3F *transform() const {
    return GetPointer<const evolution::genome::Vec3F *>(VT_TRANSFORM);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_SHAPE, 1) &&
           VerifyOffset(verifier, VT_SIZE) &&
           verifier.VerifyTable(size()) &&
           VerifyField<float>(verifier, VT_MASS_DENSITY, 4) &&
           VerifyOffset(verifier, VT_COLOR) &&
           verifier.VerifyTable(color()) &&
           VerifyOffset(verifier, VT_CHILDREN) &&
           verifier.VerifyVector(children()) &&
           verifier.VerifyVectorOfTables(children()) &&
           VerifyOffset(verifier, VT_JOINT_TO_PARENT) &&
           verifier.VerifyTable(joint_to_parent()) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyTable(transform()) &&
           verifier.EndTable();
  }
};

struct BodyNodeBuilder {
  typedef BodyNode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_shape(evolution::genome::ShapeType shape) {
    fbb_.AddElement<uint8_t>(BodyNode::VT_SHAPE, static_cast<uint8_t>(shape), 0);
  }
  void add_size(::flatbuffers::Offset<evolution::genome::Vec3F> size) {
    fbb_.AddOffset(BodyNode::VT_SIZE, size);
  }
  void add_mass_density(float mass_density) {
    fbb_.AddElement<float>(BodyNode::VT_MASS_DENSITY, mass_density, 0.0f);
  }
  void add_color(::flatbuffers::Offset<evolution::genome::Vec3F> color) {
    fbb_.AddOffset(BodyNode::VT_COLOR, color);
  }
  void add_children(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::BodyNode>>> children) {
    fbb_.AddOffset(BodyNode::VT_CHILDREN, children);
  }
  void add_joint_to_parent(::flatbuffers::Offset<evolution::genome::Joint> joint_to_parent) {
    fbb_.AddOffset(BodyNode::VT_JOINT_TO_PARENT, joint_to_parent);
  }
  void add_transform(::flatbuffers::Offset<evolution::genome::Vec3F> transform) {
    fbb_.AddOffset(BodyNode::VT_TRANSFORM, transform);
  }
  explicit BodyNodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BodyNode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BodyNode>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BodyNode> CreateBodyNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    evolution::genome::ShapeType shape = evolution::genome::ShapeType_Sphere,
    ::flatbuffers::Offset<evolution::genome::Vec3F> size = 0,
    float mass_density = 0.0f,
    ::flatbuffers::Offset<evolution::genome::Vec3F> color = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::BodyNode>>> children = 0,
    ::flatbuffers::Offset<evolution::genome::Joint> joint_to_parent = 0,
    ::flatbuffers::Offset<evolution::genome::Vec3F> transform = 0) {
  BodyNodeBuilder builder_(_fbb);
  builder_.add_transform(transform);
  builder_.add_joint_to_parent(joint_to_parent);
  builder_.add_children(children);
  builder_.add_color(color);
  builder_.add_mass_density(mass_density);
  builder_.add_size(size);
  builder_.add_shape(shape);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<BodyNode> CreateBodyNodeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    evolution::genome::ShapeType shape = evolution::genome::ShapeType_Sphere,
    ::flatbuffers::Offset<evolution::genome::Vec3F> size = 0,
    float mass_density = 0.0f,
    ::flatbuffers::Offset<evolution::genome::Vec3F> color = 0,
    const std::vector<::flatbuffers::Offset<evolution::genome::BodyNode>> *children = nullptr,
    ::flatbuffers::Offset<evolution::genome::Joint> joint_to_parent = 0,
    ::flatbuffers::Offset<evolution::genome::Vec3F> transform = 0) {
  auto children__ = children ? _fbb.CreateVector<::flatbuffers::Offset<evolution::genome::BodyNode>>(*children) : 0;
  return evolution::genome::CreateBodyNode(
      _fbb,
      shape,
      size,
      mass_density,
      color,
      children__,
      joint_to_parent,
      transform);
}

struct MLP FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MLPBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INPUT_COUNT = 4,
    VT_OUTPUT_COUNT = 6,
    VT_HIDDEN_LAYERS = 8,
    VT_WEIGHTS = 10,
    VT_BIASES = 12,
    VT_UPDATE_RATE_HZ = 14
  };
  uint32_t input_count() const {
    return GetField<uint32_t>(VT_INPUT_COUNT, 0);
  }
  uint32_t output_count() const {
    return GetField<uint32_t>(VT_OUTPUT_COUNT, 0);
  }
  const ::flatbuffers::Vector<uint32_t> *hidden_layers() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_HIDDEN_LAYERS);
  }
  const ::flatbuffers::Vector<float> *weights() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_WEIGHTS);
  }
  const ::flatbuffers::Vector<float> *biases() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_BIASES);
  }
  float update_rate_hz() const {
    return GetField<float>(VT_UPDATE_RATE_HZ, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INPUT_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_OUTPUT_COUNT, 4) &&
           VerifyOffset(verifier, VT_HIDDEN_LAYERS) &&
           verifier.VerifyVector(hidden_layers()) &&
           VerifyOffset(verifier, VT_WEIGHTS) &&
           verifier.VerifyVector(weights()) &&
           VerifyOffset(verifier, VT_BIASES) &&
           verifier.VerifyVector(biases()) &&
           VerifyField<float>(verifier, VT_UPDATE_RATE_HZ, 4) &&
           verifier.EndTable();
  }
};

struct MLPBuilder {
  typedef MLP Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_input_count(uint32_t input_count) {
    fbb_.AddElement<uint32_t>(MLP::VT_INPUT_COUNT, input_count, 0);
  }
  void add_output_count(uint32_t output_count) {
    fbb_.AddElement<uint32_t>(MLP::VT_OUTPUT_COUNT, output_count, 0);
  }
  void add_hidden_layers(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> hidden_layers) {
    fbb_.AddOffset(MLP::VT_HIDDEN_LAYERS, hidden_layers);
  }
  void add_weights(::flatbuffers::Offset<::flatbuffers::Vector<float>> weights) {
    fbb_.AddOffset(MLP::VT_WEIGHTS, weights);
  }
  void add_biases(::flatbuffers::Offset<::flatbuffers::Vector<float>> biases) {
    fbb_.AddOffset(MLP::VT_BIASES, biases);
  }
  void add_update_rate_hz(float update_rate_hz) {
    fbb_.AddElement<float>(MLP::VT_UPDATE_RATE_HZ, update_rate_hz, 0.0f);
  }
  explicit MLPBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MLP> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MLP>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MLP> CreateMLP(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t input_count = 0,
    uint32_t output_count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> hidden_layers = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> weights = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> biases = 0,
    float update_rate_hz = 0.0f) {
  MLPBuilder builder_(_fbb);
  builder_.add_update_rate_hz(update_rate_hz);
  builder_.add_biases(biases);
  builder_.add_weights(weights);
  builder_.add_hidden_layers(hidden_layers);
  builder_.add_output_count(output_count);
  builder_.add_input_count(input_count);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MLP> CreateMLPDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t input_count = 0,
    uint32_t output_count = 0,
    const std::vector<uint32_t> *hidden_layers = nullptr,
    const std::vector<float> *weights = nullptr,
    const std::vector<float> *biases = nullptr,
    float update_rate_hz = 0.0f) {
  auto hidden_layers__ = hidden_layers ? _fbb.CreateVector<uint32_t>(*hidden_layers) : 0;
  auto weights__ = weights ? _fbb.CreateVector<float>(*weights) : 0;
  auto biases__ = biases ? _fbb.CreateVector<float>(*biases) : 0;
  return evolution::genome::CreateMLP(
      _fbb,
      input_count,
      output_count,
      hidden_layers__,
      weights__,
      biases__,
      update_rate_hz);
}

struct NeatNode FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NeatNodeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TYPE = 6,
    VT_BIAS = 8,
    VT_ACT = 10
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  evolution::genome::NodeType type() const {
    return static_cast<evolution::genome::NodeType>(GetField<uint8_t>(VT_TYPE, 0));
  }
  float bias() const {
    return GetField<float>(VT_BIAS, 0.0f);
  }
  evolution::genome::Activation act() const {
    return static_cast<evolution::genome::Activation>(GetField<uint8_t>(VT_ACT, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyField<uint8_t>(verifier, VT_TYPE, 1) &&
           VerifyField<float>(verifier, VT_BIAS, 4) &&
           VerifyField<uint8_t>(verifier, VT_ACT, 1) &&
           verifier.EndTable();
  }
};

struct NeatNodeBuilder {
  typedef NeatNode Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(NeatNode::VT_ID, id, 0);
  }
  void add_type(evolution::genome::NodeType type) {
    fbb_.AddElement<uint8_t>(NeatNode::VT_TYPE, static_cast<uint8_t>(type), 0);
  }
  void add_bias(float bias) {
    fbb_.AddElement<float>(NeatNode::VT_BIAS, bias, 0.0f);
  }
  void add_act(evolution::genome::Activation act) {
    fbb_.AddElement<uint8_t>(NeatNode::VT_ACT, static_cast<uint8_t>(act), 0);
  }
  explicit NeatNodeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NeatNode> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NeatNode>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NeatNode> CreateNeatNode(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    evolution::genome::NodeType type = evolution::genome::NodeType_Input,
    float bias = 0.0f,
    evolution::genome::Activation act = evolution::genome::Activation_Linear) {
  NeatNodeBuilder builder_(_fbb);
  builder_.add_bias(bias);
  builder_.add_id(id);
  builder_.add_act(act);
  builder_.add_type(type);
  return builder_.Finish();
}

struct NeatConn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NeatConnBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_IN = 4,
    VT_OUT = 6,
    VT_WEIGHT = 8,
    VT_ENABLED = 10,
    VT_INNOVATION = 12,
    VT_RECURRENT = 14
  };
  uint32_t in() const {
    return GetField<uint32_t>(VT_IN, 0);
  }
  uint32_t out() const {
    return GetField<uint32_t>(VT_OUT, 0);
  }
  float weight() const {
    return GetField<float>(VT_WEIGHT, 0.0f);
  }
  bool enabled() const {
    return GetField<uint8_t>(VT_ENABLED, 0) != 0;
  }
  uint32_t innovation() const {
    return GetField<uint32_t>(VT_INNOVATION, 0);
  }
  bool recurrent() const {
    return GetField<uint8_t>(VT_RECURRENT, 0) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_IN, 4) &&
           VerifyField<uint32_t>(verifier, VT_OUT, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT, 4) &&
           VerifyField<uint8_t>(verifier, VT_ENABLED, 1) &&
           VerifyField<uint32_t>(verifier, VT_INNOVATION, 4) &&
           VerifyField<uint8_t>(verifier, VT_RECURRENT, 1) &&
           verifier.EndTable();
  }
};

struct NeatConnBuilder {
  typedef NeatConn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_in(uint32_t in) {
    fbb_.AddElement<uint32_t>(NeatConn::VT_IN, in, 0);
  }
  void add_out(uint32_t out) {
    fbb_.AddElement<uint32_t>(NeatConn::VT_OUT, out, 0);
  }
  void add_weight(float weight) {
    fbb_.AddElement<float>(NeatConn::VT_WEIGHT, weight, 0.0f);
  }
  void add_enabled(bool enabled) {
    fbb_.AddElement<uint8_t>(NeatConn::VT_ENABLED, static_cast<uint8_t>(enabled), 0);
  }
  void add_innovation(uint32_t innovation) {
    fbb_.AddElement<uint32_t>(NeatConn::VT_INNOVATION, innovation, 0);
  }
  void add_recurrent(bool recurrent) {
    fbb_.AddElement<uint8_t>(NeatConn::VT_RECURRENT, static_cast<uint8_t>(recurrent), 0);
  }
  explicit NeatConnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NeatConn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NeatConn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NeatConn> CreateNeatConn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t in = 0,
    uint32_t out = 0,
    float weight = 0.0f,
    bool enabled = false,
    uint32_t innovation = 0,
    bool recurrent = false) {
  NeatConnBuilder builder_(_fbb);
  builder_.add_innovation(innovation);
  builder_.add_weight(weight);
  builder_.add_out(out);
  builder_.add_in(in);
  builder_.add_recurrent(recurrent);
  builder_.add_enabled(enabled);
  return builder_.Finish();
}

struct NEAT FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef NEATBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INPUT_COUNT = 4,
    VT_OUTPUT_COUNT = 6,
    VT_NODES = 8,
    VT_CONNS = 10,
    VT_UPDATE_RATE_HZ = 12
  };
  uint32_t input_count() const {
    return GetField<uint32_t>(VT_INPUT_COUNT, 0);
  }
  uint32_t output_count() const {
    return GetField<uint32_t>(VT_OUTPUT_COUNT, 0);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::NeatNode>> *nodes() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::NeatNode>> *>(VT_NODES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::NeatConn>> *conns() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::NeatConn>> *>(VT_CONNS);
  }
  float update_rate_hz() const {
    return GetField<float>(VT_UPDATE_RATE_HZ, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_INPUT_COUNT, 4) &&
           VerifyField<uint32_t>(verifier, VT_OUTPUT_COUNT, 4) &&
           VerifyOffset(verifier, VT_NODES) &&
           verifier.VerifyVector(nodes()) &&
           verifier.VerifyVectorOfTables(nodes()) &&
           VerifyOffset(verifier, VT_CONNS) &&
           verifier.VerifyVector(conns()) &&
           verifier.VerifyVectorOfTables(conns()) &&
           VerifyField<float>(verifier, VT_UPDATE_RATE_HZ, 4) &&
           verifier.EndTable();
  }
};

struct NEATBuilder {
  typedef NEAT Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_input_count(uint32_t input_count) {
    fbb_.AddElement<uint32_t>(NEAT::VT_INPUT_COUNT, input_count, 0);
  }
  void add_output_count(uint32_t output_count) {
    fbb_.AddElement<uint32_t>(NEAT::VT_OUTPUT_COUNT, output_count, 0);
  }
  void add_nodes(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::NeatNode>>> nodes) {
    fbb_.AddOffset(NEAT::VT_NODES, nodes);
  }
  void add_conns(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::NeatConn>>> conns) {
    fbb_.AddOffset(NEAT::VT_CONNS, conns);
  }
  void add_update_rate_hz(float update_rate_hz) {
    fbb_.AddElement<float>(NEAT::VT_UPDATE_RATE_HZ, update_rate_hz, 0.0f);
  }
  explicit NEATBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<NEAT> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<NEAT>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<NEAT> CreateNEAT(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t input_count = 0,
    uint32_t output_count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::NeatNode>>> nodes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::NeatConn>>> conns = 0,
    float update_rate_hz = 0.0f) {
  NEATBuilder builder_(_fbb);
  builder_.add_update_rate_hz(update_rate_hz);
  builder_.add_conns(conns);
  builder_.add_nodes(nodes);
  builder_.add_output_count(output_count);
  builder_.add_input_count(input_count);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<NEAT> CreateNEATDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t input_count = 0,
    uint32_t output_count = 0,
    const std::vector<::flatbuffers::Offset<evolution::genome::NeatNode>> *nodes = nullptr,
    const std::vector<::flatbuffers::Offset<evolution::genome::NeatConn>> *conns = nullptr,
    float update_rate_hz = 0.0f) {
  auto nodes__ = nodes ? _fbb.CreateVector<::flatbuffers::Offset<evolution::genome::NeatNode>>(*nodes) : 0;
  auto conns__ = conns ? _fbb.CreateVector<::flatbuffers::Offset<evolution::genome::NeatConn>>(*conns) : 0;
  return evolution::genome::CreateNEAT(
      _fbb,
      input_count,
      output_count,
      nodes__,
      conns__,
      update_rate_hz);
}

struct ModulePlasticity FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ModulePlasticityBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BIAS_COEFFS = 4,
    VT_SCALE_COEFFS = 6,
    VT_TRACE_GAIN = 8,
    VT_TRACE_DECAY = 10
  };
  const ::flatbuffers::Vector<float> *bias_coeffs() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_BIAS_COEFFS);
  }
  const ::flatbuffers::Vector<float> *scale_coeffs() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_SCALE_COEFFS);
  }
  float trace_gain() const {
    return GetField<float>(VT_TRACE_GAIN, 0.0f);
  }
  float trace_decay() const {
    return GetField<float>(VT_TRACE_DECAY, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_BIAS_COEFFS) &&
           verifier.VerifyVector(bias_coeffs()) &&
           VerifyOffset(verifier, VT_SCALE_COEFFS) &&
           verifier.VerifyVector(scale_coeffs()) &&
           VerifyField<float>(verifier, VT_TRACE_GAIN, 4) &&
           VerifyField<float>(verifier, VT_TRACE_DECAY, 4) &&
           verifier.EndTable();
  }
};

struct ModulePlasticityBuilder {
  typedef ModulePlasticity Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_bias_coeffs(::flatbuffers::Offset<::flatbuffers::Vector<float>> bias_coeffs) {
    fbb_.AddOffset(ModulePlasticity::VT_BIAS_COEFFS, bias_coeffs);
  }
  void add_scale_coeffs(::flatbuffers::Offset<::flatbuffers::Vector<float>> scale_coeffs) {
    fbb_.AddOffset(ModulePlasticity::VT_SCALE_COEFFS, scale_coeffs);
  }
  void add_trace_gain(float trace_gain) {
    fbb_.AddElement<float>(ModulePlasticity::VT_TRACE_GAIN, trace_gain, 0.0f);
  }
  void add_trace_decay(float trace_decay) {
    fbb_.AddElement<float>(ModulePlasticity::VT_TRACE_DECAY, trace_decay, 0.0f);
  }
  explicit ModulePlasticityBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ModulePlasticity> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ModulePlasticity>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ModulePlasticity> CreateModulePlasticity(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> bias_coeffs = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> scale_coeffs = 0,
    float trace_gain = 0.0f,
    float trace_decay = 0.0f) {
  ModulePlasticityBuilder builder_(_fbb);
  builder_.add_trace_decay(trace_decay);
  builder_.add_trace_gain(trace_gain);
  builder_.add_scale_coeffs(scale_coeffs);
  builder_.add_bias_coeffs(bias_coeffs);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ModulePlasticity> CreateModulePlasticityDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<float> *bias_coeffs = nullptr,
    const std::vector<float> *scale_coeffs = nullptr,
    float trace_gain = 0.0f,
    float trace_decay = 0.0f) {
  auto bias_coeffs__ = bias_coeffs ? _fbb.CreateVector<float>(*bias_coeffs) : 0;
  auto scale_coeffs__ = scale_coeffs ? _fbb.CreateVector<float>(*scale_coeffs) : 0;
  return evolution::genome::CreateModulePlasticity(
      _fbb,
      bias_coeffs__,
      scale_coeffs__,
      trace_gain,
      trace_decay);
}

struct BrainModule FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BrainModuleBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_KIND = 4,
    VT_MLP = 6,
    VT_NEAT = 8,
    VT_PLASTICITY = 10
  };
  evolution::genome::BrainKind kind() const {
    return static_cast<evolution::genome::BrainKind>(GetField<uint8_t>(VT_KIND, 0));
  }
  const evolution::genome::MLP *mlp() const {
    return GetPointer<const evolution::genome::MLP *>(VT_MLP);
  }
  const evolution::genome::NEAT *neat() const {
    return GetPointer<const evolution::genome::NEAT *>(VT_NEAT);
  }
  const evolution::genome::ModulePlasticity *plasticity() const {
    return GetPointer<const evolution::genome::ModulePlasticity *>(VT_PLASTICITY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_KIND, 1) &&
           VerifyOffset(verifier, VT_MLP) &&
           verifier.VerifyTable(mlp()) &&
           VerifyOffset(verifier, VT_NEAT) &&
           verifier.VerifyTable(neat()) &&
           VerifyOffset(verifier, VT_PLASTICITY) &&
           verifier.VerifyTable(plasticity()) &&
           verifier.EndTable();
  }
};

struct BrainModuleBuilder {
  typedef BrainModule Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_kind(evolution::genome::BrainKind kind) {
    fbb_.AddElement<uint8_t>(BrainModule::VT_KIND, static_cast<uint8_t>(kind), 0);
  }
  void add_mlp(::flatbuffers::Offset<evolution::genome::MLP> mlp) {
    fbb_.AddOffset(BrainModule::VT_MLP, mlp);
  }
  void add_neat(::flatbuffers::Offset<evolution::genome::NEAT> neat) {
    fbb_.AddOffset(BrainModule::VT_NEAT, neat);
  }
  void add_plasticity(::flatbuffers::Offset<evolution::genome::ModulePlasticity> plasticity) {
    fbb_.AddOffset(BrainModule::VT_PLASTICITY, plasticity);
  }
  explicit BrainModuleBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BrainModule> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BrainModule>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BrainModule> CreateBrainModule(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    evolution::genome::BrainKind kind = evolution::genome::BrainKind_MLP,
    ::flatbuffers::Offset<evolution::genome::MLP> mlp = 0,
    ::flatbuffers::Offset<evolution::genome::NEAT> neat = 0,
    ::flatbuffers::Offset<evolution::genome::ModulePlasticity> plasticity = 0) {
  BrainModuleBuilder builder_(_fbb);
  builder_.add_plasticity(plasticity);
  builder_.add_neat(neat);
  builder_.add_mlp(mlp);
  builder_.add_kind(kind);
  return builder_.Finish();
}

struct BrainGating FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BrainGatingBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTEXT_SIZE = 4,
    VT_EPSILON = 6,
    VT_MLP = 8
  };
  uint32_t context_size() const {
    return GetField<uint32_t>(VT_CONTEXT_SIZE, 0);
  }
  float epsilon() const {
    return GetField<float>(VT_EPSILON, 0.05f);
  }
  const evolution::genome::MLP *mlp() const {
    return GetPointer<const evolution::genome::MLP *>(VT_MLP);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CONTEXT_SIZE, 4) &&
           VerifyField<float>(verifier, VT_EPSILON, 4) &&
           VerifyOffset(verifier, VT_MLP) &&
           verifier.VerifyTable(mlp()) &&
           verifier.EndTable();
  }
};

struct BrainGatingBuilder {
  typedef BrainGating Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_context_size(uint32_t context_size) {
    fbb_.AddElement<uint32_t>(BrainGating::VT_CONTEXT_SIZE, context_size, 0);
  }
  void add_epsilon(float epsilon) {
    fbb_.AddElement<float>(BrainGating::VT_EPSILON, epsilon, 0.05f);
  }
  void add_mlp(::flatbuffers::Offset<evolution::genome::MLP> mlp) {
    fbb_.AddOffset(BrainGating::VT_MLP, mlp);
  }
  explicit BrainGatingBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BrainGating> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BrainGating>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BrainGating> CreateBrainGating(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t context_size = 0,
    float epsilon = 0.05f,
    ::flatbuffers::Offset<evolution::genome::MLP> mlp = 0) {
  BrainGatingBuilder builder_(_fbb);
  builder_.add_mlp(mlp);
  builder_.add_epsilon(epsilon);
  builder_.add_context_size(context_size);
  return builder_.Finish();
}

struct PreferenceNet FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PreferenceNetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MLP = 4,
    VT_TRAIT_SCALE = 6
  };
  const evolution::genome::MLP *mlp() const {
    return GetPointer<const evolution::genome::MLP *>(VT_MLP);
  }
  float trait_scale() const {
    return GetField<float>(VT_TRAIT_SCALE, 1.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_MLP) &&
           verifier.VerifyTable(mlp()) &&
           VerifyField<float>(verifier, VT_TRAIT_SCALE, 4) &&
           verifier.EndTable();
  }
};

struct PreferenceNetBuilder {
  typedef PreferenceNet Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mlp(::flatbuffers::Offset<evolution::genome::MLP> mlp) {
    fbb_.AddOffset(PreferenceNet::VT_MLP, mlp);
  }
  void add_trait_scale(float trait_scale) {
    fbb_.AddElement<float>(PreferenceNet::VT_TRAIT_SCALE, trait_scale, 1.0f);
  }
  explicit PreferenceNetBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PreferenceNet> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PreferenceNet>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PreferenceNet> CreatePreferenceNet(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<evolution::genome::MLP> mlp = 0,
    float trait_scale = 1.0f) {
  PreferenceNetBuilder builder_(_fbb);
  builder_.add_trait_scale(trait_scale);
  builder_.add_mlp(mlp);
  return builder_.Finish();
}

struct Mutator FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MutatorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MUTATE_RATE_STRUCT = 4,
    VT_MUTATE_RATE_PARAM = 6,
    VT_WEIGHT_SIGMA = 8,
    VT_MODULE_DUPLICATION_RATE = 10
  };
  float mutate_rate_struct() const {
    return GetField<float>(VT_MUTATE_RATE_STRUCT, 0.05f);
  }
  float mutate_rate_param() const {
    return GetField<float>(VT_MUTATE_RATE_PARAM, 0.2f);
  }
  float weight_sigma() const {
    return GetField<float>(VT_WEIGHT_SIGMA, 0.2f);
  }
  float module_duplication_rate() const {
    return GetField<float>(VT_MODULE_DUPLICATION_RATE, 0.01f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_MUTATE_RATE_STRUCT, 4) &&
           VerifyField<float>(verifier, VT_MUTATE_RATE_PARAM, 4) &&
           VerifyField<float>(verifier, VT_WEIGHT_SIGMA, 4) &&
           VerifyField<float>(verifier, VT_MODULE_DUPLICATION_RATE, 4) &&
           verifier.EndTable();
  }
};

struct MutatorBuilder {
  typedef Mutator Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mutate_rate_struct(float mutate_rate_struct) {
    fbb_.AddElement<float>(Mutator::VT_MUTATE_RATE_STRUCT, mutate_rate_struct, 0.05f);
  }
  void add_mutate_rate_param(float mutate_rate_param) {
    fbb_.AddElement<float>(Mutator::VT_MUTATE_RATE_PARAM, mutate_rate_param, 0.2f);
  }
  void add_weight_sigma(float weight_sigma) {
    fbb_.AddElement<float>(Mutator::VT_WEIGHT_SIGMA, weight_sigma, 0.2f);
  }
  void add_module_duplication_rate(float module_duplication_rate) {
    fbb_.AddElement<float>(Mutator::VT_MODULE_DUPLICATION_RATE, module_duplication_rate, 0.01f);
  }
  explicit MutatorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Mutator> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Mutator>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Mutator> CreateMutator(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float mutate_rate_struct = 0.05f,
    float mutate_rate_param = 0.2f,
    float weight_sigma = 0.2f,
    float module_duplication_rate = 0.01f) {
  MutatorBuilder builder_(_fbb);
  builder_.add_module_duplication_rate(module_duplication_rate);
  builder_.add_weight_sigma(weight_sigma);
  builder_.add_mutate_rate_param(mutate_rate_param);
  builder_.add_mutate_rate_struct(mutate_rate_struct);
  return builder_.Finish();
}

struct LifeStage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LifeStageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_AGE = 4,
    VT_GATE_MULTIPLIERS = 6,
    VT_ENERGY_SCALE = 8,
    VT_SIZE_SCALE = 10,
    VT_REPRODUCTION_ALLOWED = 12
  };
  float age() const {
    return GetField<float>(VT_AGE, 0.0f);
  }
  const ::flatbuffers::Vector<float> *gate_multipliers() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_GATE_MULTIPLIERS);
  }
  float energy_scale() const {
    return GetField<float>(VT_ENERGY_SCALE, 1.0f);
  }
  float size_scale() const {
    return GetField<float>(VT_SIZE_SCALE, 1.0f);
  }
  bool reproduction_allowed() const {
    return GetField<uint8_t>(VT_REPRODUCTION_ALLOWED, 1) != 0;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_AGE, 4) &&
           VerifyOffset(verifier, VT_GATE_MULTIPLIERS) &&
           verifier.VerifyVector(gate_multipliers()) &&
           VerifyField<float>(verifier, VT_ENERGY_SCALE, 4) &&
           VerifyField<float>(verifier, VT_SIZE_SCALE, 4) &&
           VerifyField<uint8_t>(verifier, VT_REPRODUCTION_ALLOWED, 1) &&
           verifier.EndTable();
  }
};

struct LifeStageBuilder {
  typedef LifeStage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_age(float age) {
    fbb_.AddElement<float>(LifeStage::VT_AGE, age, 0.0f);
  }
  void add_gate_multipliers(::flatbuffers::Offset<::flatbuffers::Vector<float>> gate_multipliers) {
    fbb_.AddOffset(LifeStage::VT_GATE_MULTIPLIERS, gate_multipliers);
  }
  void add_energy_scale(float energy_scale) {
    fbb_.AddElement<float>(LifeStage::VT_ENERGY_SCALE, energy_scale, 1.0f);
  }
  void add_size_scale(float size_scale) {
    fbb_.AddElement<float>(LifeStage::VT_SIZE_SCALE, size_scale, 1.0f);
  }
  void add_reproduction_allowed(bool reproduction_allowed) {
    fbb_.AddElement<uint8_t>(LifeStage::VT_REPRODUCTION_ALLOWED, static_cast<uint8_t>(reproduction_allowed), 1);
  }
  explicit LifeStageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LifeStage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LifeStage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LifeStage> CreateLifeStage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float age = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> gate_multipliers = 0,
    float energy_scale = 1.0f,
    float size_scale = 1.0f,
    bool reproduction_allowed = true) {
  LifeStageBuilder builder_(_fbb);
  builder_.add_size_scale(size_scale);
  builder_.add_energy_scale(energy_scale);
  builder_.add_gate_multipliers(gate_multipliers);
  builder_.add_age(age);
  builder_.add_reproduction_allowed(reproduction_allowed);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LifeStage> CreateLifeStageDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float age = 0.0f,
    const std::vector<float> *gate_multipliers = nullptr,
    float energy_scale = 1.0f,
    float size_scale = 1.0f,
    bool reproduction_allowed = true) {
  auto gate_multipliers__ = gate_multipliers ? _fbb.CreateVector<float>(*gate_multipliers) : 0;
  return evolution::genome::CreateLifeStage(
      _fbb,
      age,
      gate_multipliers__,
      energy_scale,
      size_scale,
      reproduction_allowed);
}

struct TraitsCache FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TraitsCacheBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MASS = 4,
    VT_BASAL_RATE = 6,
    VT_BRAIN_COST = 8,
    VT_BRAIN_PARAMS = 10,
    VT_MODULE_COUNT = 12,
    VT_TRAIT_LATENT = 14
  };
  float mass() const {
    return GetField<float>(VT_MASS, 0.0f);
  }
  float basal_rate() const {
    return GetField<float>(VT_BASAL_RATE, 0.0f);
  }
  float brain_cost() const {
    return GetField<float>(VT_BRAIN_COST, 0.0f);
  }
  float brain_params() const {
    return GetField<float>(VT_BRAIN_PARAMS, 0.0f);
  }
  uint16_t module_count() const {
    return GetField<uint16_t>(VT_MODULE_COUNT, 0);
  }
  const ::flatbuffers::Vector<float> *trait_latent() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_TRAIT_LATENT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_MASS, 4) &&
           VerifyField<float>(verifier, VT_BASAL_RATE, 4) &&
           VerifyField<float>(verifier, VT_BRAIN_COST, 4) &&
           VerifyField<float>(verifier, VT_BRAIN_PARAMS, 4) &&
           VerifyField<uint16_t>(verifier, VT_MODULE_COUNT, 2) &&
           VerifyOffset(verifier, VT_TRAIT_LATENT) &&
           verifier.VerifyVector(trait_latent()) &&
           verifier.EndTable();
  }
};

struct TraitsCacheBuilder {
  typedef TraitsCache Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mass(float mass) {
    fbb_.AddElement<float>(TraitsCache::VT_MASS, mass, 0.0f);
  }
  void add_basal_rate(float basal_rate) {
    fbb_.AddElement<float>(TraitsCache::VT_BASAL_RATE, basal_rate, 0.0f);
  }
  void add_brain_cost(float brain_cost) {
    fbb_.AddElement<float>(TraitsCache::VT_BRAIN_COST, brain_cost, 0.0f);
  }
  void add_brain_params(float brain_params) {
    fbb_.AddElement<float>(TraitsCache::VT_BRAIN_PARAMS, brain_params, 0.0f);
  }
  void add_module_count(uint16_t module_count) {
    fbb_.AddElement<uint16_t>(TraitsCache::VT_MODULE_COUNT, module_count, 0);
  }
  void add_trait_latent(::flatbuffers::Offset<::flatbuffers::Vector<float>> trait_latent) {
    fbb_.AddOffset(TraitsCache::VT_TRAIT_LATENT, trait_latent);
  }
  explicit TraitsCacheBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TraitsCache> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TraitsCache>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TraitsCache> CreateTraitsCache(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float mass = 0.0f,
    float basal_rate = 0.0f,
    float brain_cost = 0.0f,
    float brain_params = 0.0f,
    uint16_t module_count = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> trait_latent = 0) {
  TraitsCacheBuilder builder_(_fbb);
  builder_.add_trait_latent(trait_latent);
  builder_.add_brain_params(brain_params);
  builder_.add_brain_cost(brain_cost);
  builder_.add_basal_rate(basal_rate);
  builder_.add_mass(mass);
  builder_.add_module_count(module_count);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TraitsCache> CreateTraitsCacheDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float mass = 0.0f,
    float basal_rate = 0.0f,
    float brain_cost = 0.0f,
    float brain_params = 0.0f,
    uint16_t module_count = 0,
    const std::vector<float> *trait_latent = nullptr) {
  auto trait_latent__ = trait_latent ? _fbb.CreateVector<float>(*trait_latent) : 0;
  return evolution::genome::CreateTraitsCache(
      _fbb,
      mass,
      basal_rate,
      brain_cost,
      brain_params,
      module_count,
      trait_latent__);
}

struct Genome FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GenomeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VERSION = 4,
    VT_ID = 6,
    VT_GENERATION = 8,
    VT_PARENTS = 10,
    VT_RNG_SEED = 12,
    VT_BODY = 14,
    VT_BRAIN_KIND = 16,
    VT_MLP = 18,
    VT_NEAT = 20,
    VT_MODULES = 22,
    VT_GATING = 24,
    VT_PREFERENCE = 26,
    VT_MUTATOR = 28,
    VT_HOTSPOTS = 30,
    VT_LIFE_STAGES = 32,
    VT_CACHED = 34,
    VT_DIET = 36,
    VT_ATTACK_REACH = 38,
    VT_ATTACK_POWER = 40,
    VT_SPEED_TRAIT = 42
  };
  uint16_t version() const {
    return GetField<uint16_t>(VT_VERSION, 0);
  }
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  uint32_t generation() const {
    return GetField<uint32_t>(VT_GENERATION, 0);
  }
  const ::flatbuffers::Vector<uint64_t> *parents() const {
    return GetPointer<const ::flatbuffers::Vector<uint64_t> *>(VT_PARENTS);
  }
  uint64_t rng_seed() const {
    return GetField<uint64_t>(VT_RNG_SEED, 0);
  }
  const evolution::genome::BodyNode *body() const {
    return GetPointer<const evolution::genome::BodyNode *>(VT_BODY);
  }
  evolution::genome::BrainKind brain_kind() const {
    return static_cast<evolution::genome::BrainKind>(GetField<uint8_t>(VT_BRAIN_KIND, 0));
  }
  const evolution::genome::MLP *mlp() const {
    return GetPointer<const evolution::genome::MLP *>(VT_MLP);
  }
  const evolution::genome::NEAT *neat() const {
    return GetPointer<const evolution::genome::NEAT *>(VT_NEAT);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::BrainModule>> *modules() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::BrainModule>> *>(VT_MODULES);
  }
  const evolution::genome::BrainGating *gating() const {
    return GetPointer<const evolution::genome::BrainGating *>(VT_GATING);
  }
  const evolution::genome::PreferenceNet *preference() const {
    return GetPointer<const evolution::genome::PreferenceNet *>(VT_PREFERENCE);
  }
  const evolution::genome::Mutator *mutator() const {
    return GetPointer<const evolution::genome::Mutator *>(VT_MUTATOR);
  }
  const ::flatbuffers::Vector<uint32_t> *hotspots() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_HOTSPOTS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::LifeStage>> *life_stages() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::LifeStage>> *>(VT_LIFE_STAGES);
  }
  const evolution::genome::TraitsCache *cached() const {
    return GetPointer<const evolution::genome::TraitsCache *>(VT_CACHED);
  }
  /// Dietary preference determining feeding behavior.
  evolution::genome::DietPreference diet() const {
    return static_cast<evolution::genome::DietPreference>(GetField<uint8_t>(VT_DIET, 0));
  }
  /// Attack reach for carnivores (meters).
  float attack_reach() const {
    return GetField<float>(VT_ATTACK_REACH, 1.5f);
  }
  /// Energy drain rate when attacking prey (energy/second).
  float attack_power() const {
    return GetField<float>(VT_ATTACK_POWER, 8.0f);
  }
  /// Movement speed multiplier (1.0 = baseline).
  float speed_trait() const {
    return GetField<float>(VT_SPEED_TRAIT, 1.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_VERSION, 2) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<uint32_t>(verifier, VT_GENERATION, 4) &&
           VerifyOffset(verifier, VT_PARENTS) &&
           verifier.VerifyVector(parents()) &&
           VerifyField<uint64_t>(verifier, VT_RNG_SEED, 8) &&
           VerifyOffset(verifier, VT_BODY) &&
           verifier.VerifyTable(body()) &&
           VerifyField<uint8_t>(verifier, VT_BRAIN_KIND, 1) &&
           VerifyOffset(verifier, VT_MLP) &&
           verifier.VerifyTable(mlp()) &&
           VerifyOffset(verifier, VT_NEAT) &&
           verifier.VerifyTable(neat()) &&
           VerifyOffset(verifier, VT_MODULES) &&
           verifier.VerifyVector(modules()) &&
           verifier.VerifyVectorOfTables(modules()) &&
           VerifyOffset(verifier, VT_GATING) &&
           verifier.VerifyTable(gating()) &&
           VerifyOffset(verifier, VT_PREFERENCE) &&
           verifier.VerifyTable(preference()) &&
           VerifyOffset(verifier, VT_MUTATOR) &&
           verifier.VerifyTable(mutator()) &&
           VerifyOffset(verifier, VT_HOTSPOTS) &&
           verifier.VerifyVector(hotspots()) &&
           VerifyOffset(verifier, VT_LIFE_STAGES) &&
           verifier.VerifyVector(life_stages()) &&
           verifier.VerifyVectorOfTables(life_stages()) &&
           VerifyOffset(verifier, VT_CACHED) &&
           verifier.VerifyTable(cached()) &&
           VerifyField<uint8_t>(verifier, VT_DIET, 1) &&
           VerifyField<float>(verifier, VT_ATTACK_REACH, 4) &&
           VerifyField<float>(verifier, VT_ATTACK_POWER, 4) &&
           VerifyField<float>(verifier, VT_SPEED_TRAIT, 4) &&
           verifier.EndTable();
  }
};

struct GenomeBuilder {
  typedef Genome Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_version(uint16_t version) {
    fbb_.AddElement<uint16_t>(Genome::VT_VERSION, version, 0);
  }
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Genome::VT_ID, id, 0);
  }
  void add_generation(uint32_t generation) {
    fbb_.AddElement<uint32_t>(Genome::VT_GENERATION, generation, 0);
  }
  void add_parents(::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> parents) {
    fbb_.AddOffset(Genome::VT_PARENTS, parents);
  }
  void add_rng_seed(uint64_t rng_seed) {
    fbb_.AddElement<uint64_t>(Genome::VT_RNG_SEED, rng_seed, 0);
  }
  void add_body(::flatbuffers::Offset<evolution::genome::BodyNode> body) {
    fbb_.AddOffset(Genome::VT_BODY, body);
  }
  void add_brain_kind(evolution::genome::BrainKind brain_kind) {
    fbb_.AddElement<uint8_t>(Genome::VT_BRAIN_KIND, static_cast<uint8_t>(brain_kind), 0);
  }
  void add_mlp(::flatbuffers::Offset<evolution::genome::MLP> mlp) {
    fbb_.AddOffset(Genome::VT_MLP, mlp);
  }
  void add_neat(::flatbuffers::Offset<evolution::genome::NEAT> neat) {
    fbb_.AddOffset(Genome::VT_NEAT, neat);
  }
  void add_modules(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::BrainModule>>> modules) {
    fbb_.AddOffset(Genome::VT_MODULES, modules);
  }
  void add_gating(::flatbuffers::Offset<evolution::genome::BrainGating> gating) {
    fbb_.AddOffset(Genome::VT_GATING, gating);
  }
  void add_preference(::flatbuffers::Offset<evolution::genome::PreferenceNet> preference) {
    fbb_.AddOffset(Genome::VT_PREFERENCE, preference);
  }
  void add_mutator(::flatbuffers::Offset<evolution::genome::Mutator> mutator) {
    fbb_.AddOffset(Genome::VT_MUTATOR, mutator);
  }
  void add_hotspots(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> hotspots) {
    fbb_.AddOffset(Genome::VT_HOTSPOTS, hotspots);
  }
  void add_life_stages(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::LifeStage>>> life_stages) {
    fbb_.AddOffset(Genome::VT_LIFE_STAGES, life_stages);
  }
  void add_cached(::flatbuffers::Offset<evolution::genome::TraitsCache> cached) {
    fbb_.AddOffset(Genome::VT_CACHED, cached);
  }
  void add_diet(evolution::genome::DietPreference diet) {
    fbb_.AddElement<uint8_t>(Genome::VT_DIET, static_cast<uint8_t>(diet), 0);
  }
  void add_attack_reach(float attack_reach) {
    fbb_.AddElement<float>(Genome::VT_ATTACK_REACH, attack_reach, 1.5f);
  }
  void add_attack_power(float attack_power) {
    fbb_.AddElement<float>(Genome::VT_ATTACK_POWER, attack_power, 8.0f);
  }
  void add_speed_trait(float speed_trait) {
    fbb_.AddElement<float>(Genome::VT_SPEED_TRAIT, speed_trait, 1.0f);
  }
  explicit GenomeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Genome> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Genome>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Genome> CreateGenome(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t version = 0,
    uint64_t id = 0,
    uint32_t generation = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint64_t>> parents = 0,
    uint64_t rng_seed = 0,
    ::flatbuffers::Offset<evolution::genome::BodyNode> body = 0,
    evolution::genome::BrainKind brain_kind = evolution::genome::BrainKind_MLP,
    ::flatbuffers::Offset<evolution::genome::MLP> mlp = 0,
    ::flatbuffers::Offset<evolution::genome::NEAT> neat = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::BrainModule>>> modules = 0,
    ::flatbuffers::Offset<evolution::genome::BrainGating> gating = 0,
    ::flatbuffers::Offset<evolution::genome::PreferenceNet> preference = 0,
    ::flatbuffers::Offset<evolution::genome::Mutator> mutator = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> hotspots = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<evolution::genome::LifeStage>>> life_stages = 0,
    ::flatbuffers::Offset<evolution::genome::TraitsCache> cached = 0,
    evolution::genome::DietPreference diet = evolution::genome::DietPreference_Herbivore,
    float attack_reach = 1.5f,
    float attack_power = 8.0f,
    float speed_trait = 1.0f) {
  GenomeBuilder builder_(_fbb);
  builder_.add_rng_seed(rng_seed);
  builder_.add_id(id);
  builder_.add_speed_trait(speed_trait);
  builder_.add_attack_power(attack_power);
  builder_.add_attack_reach(attack_reach);
  builder_.add_cached(cached);
  builder_.add_life_stages(life_stages);
  builder_.add_hotspots(hotspots);
  builder_.add_mutator(mutator);
  builder_.add_preference(preference);
  builder_.add_gating(gating);
  builder_.add_modules(modules);
  builder_.add_neat(neat);
  builder_.add_mlp(mlp);
  builder_.add_body(body);
  builder_.add_parents(parents);
  builder_.add_generation(generation);
  builder_.add_version(version);
  builder_.add_diet(diet);
  builder_.add_brain_kind(brain_kind);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Genome> CreateGenomeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t version = 0,
    uint64_t id = 0,
    uint32_t generation = 0,
    const std::vector<uint64_t> *parents = nullptr,
    uint64_t rng_seed = 0,
    ::flatbuffers::Offset<evolution::genome::BodyNode> body = 0,
    evolution::genome::BrainKind brain_kind = evolution::genome::BrainKind_MLP,
    ::flatbuffers::Offset<evolution::genome::MLP> mlp = 0,
    ::flatbuffers::Offset<evolution::genome::NEAT> neat = 0,
    const std::vector<::flatbuffers::Offset<evolution::genome::BrainModule>> *modules = nullptr,
    ::flatbuffers::Offset<evolution::genome::BrainGating> gating = 0,
    ::flatbuffers::Offset<evolution::genome::PreferenceNet> preference = 0,
    ::flatbuffers::Offset<evolution::genome::Mutator> mutator = 0,
    const std::vector<uint32_t> *hotspots = nullptr,
    const std::vector<::flatbuffers::Offset<evolution::genome::LifeStage>> *life_stages = nullptr,
    ::flatbuffers::Offset<evolution::genome::TraitsCache> cached = 0,
    evolution::genome::DietPreference diet = evolution::genome::DietPreference_Herbivore,
    float attack_reach = 1.5f,
    float attack_power = 8.0f,
    float speed_trait = 1.0f) {
  auto parents__ = parents ? _fbb.CreateVector<uint64_t>(*parents) : 0;
  auto modules__ = modules ? _fbb.CreateVector<::flatbuffers::Offset<evolution::genome::BrainModule>>(*modules) : 0;
  auto hotspots__ = hotspots ? _fbb.CreateVector<uint32_t>(*hotspots) : 0;
  auto life_stages__ = life_stages ? _fbb.CreateVector<::flatbuffers::Offset<evolution::genome::LifeStage>>(*life_stages) : 0;
  return evolution::genome::CreateGenome(
      _fbb,
      version,
      id,
      generation,
      parents__,
      rng_seed,
      body,
      brain_kind,
      mlp,
      neat,
      modules__,
      gating,
      preference,
      mutator,
      hotspots__,
      life_stages__,
      cached,
      diet,
      attack_reach,
      attack_power,
      speed_trait);
}

inline const evolution::genome::Genome *GetGenome(const void *buf) {
  return ::flatbuffers::GetRoot<evolution::genome::Genome>(buf);
}

inline const evolution::genome::Genome *GetSizePrefixedGenome(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<evolution::genome::Genome>(buf);
}

inline bool VerifyGenomeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<evolution::genome::Genome>(nullptr);
}

inline bool VerifySizePrefixedGenomeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<evolution::genome::Genome>(nullptr);
}

inline void FinishGenomeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<evolution::genome::Genome> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedGenomeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<evolution::genome::Genome> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace genome
}  // namespace evolution

#endif  // FLATBUFFERS_GENERATED_GENOME_EVOLUTION_GENOME_H_
